### PR TITLE
`log()` second PR

### PR DESCRIPTION
**Pull request by Dazeofcitywalk**
Fixed the bug in row writing.

### CODE REVIEW

**Comment by YLee2121** [comment]
image

It still has some bugs. For the first time writing log, it can successfully update the `CSV` file. However, for the second time adding the log, it doesn't work anymore. The possible reason might be you also write the row index into the `CSV` file. 


Capture

**Comment by Dazeofcitywalk** [comment]
I used parameter `index=None` to change the export process.
Also I wonder if I could test my modification before merging. Currently I test it by building up some new code example (which is not linked with the calendar CLI process)

**Comment by YLee2121** [comment]
> I used parameter `index=None` to change the export process. Also I wonder if I could test my modification before merging. Currently I test it by building up some new code example (which is not linked with the calendar CLI process)

#15 has the testing code, I have not finished the PR. If you are interested, it's using the `pytest` framework.

**Review by YLee2121 — APPROVED** [review]
Pass

**Pull request merged**
